
# APPLICATION
spring.application.name=eureka-service


# SERVER
server.port=8761


# EUREKA INSTANCE
eureka.instance.hostname=localhost


# EUREKA CLIENT
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
#eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/


# EUREKA SERVER
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.response-cache-update-interval-ms=5000


# ACTUATOR
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*