server.port=8085


spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_notification_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update

# Definisanje PostgreSQL dijalekta za Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Prikazivanje i formatiranje SQL upita u konzoli (odlično za debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always