spring.application.name=config-service

# Port na kome standardno radi Config Server
server.port=8888

# Podešavanje da Config Server čita fajlove sa lokalnog fajl sistema (umesto sa Git-a)
spring.profiles.active=native

spring.cloud.config.server.native.search-locations=file:../config-repo